ITEMS = {
    "001": {
        "itemId": "001",
        "itemName": "二酸化硫黄",
        "simpleName": "SO2",
        "iniVal": "0",
        "scale": None,
        "unit": "ppb",
        "od": 10,
    },
    "002": {
        "itemId": "002",
        "itemName": "光化学オキシダント",
        "simpleName": "OX",
        "iniVal": "0",
        "scale": None,
        "unit": "ppb",
        "od": 20,
    },
    "003": {
        "itemId": "003",
        "itemName": "一酸化窒素",
        "simpleName": "NO",
        "iniVal": "0",
        "scale": None,
        "unit": "ppb",
        "od": 30,
    },
    "004": {
        "itemId": "004",
        "itemName": "二酸化窒素",
        "simpleName": "NO2",
        "iniVal": "0",
        "scale": None,
        "unit": "ppb",
        "od": 40,
    },
    "005": {
        "itemId": "005",
        "itemName": "窒素酸化物",
        "simpleName": "NOX",
        "iniVal": "0",
        "scale": None,
        "unit": "ppb",
        "od": 50,
    },
    "007": {
        "itemId": "007",
        "itemName": "一酸化炭素",
        "simpleName": "CO",
        "iniVal": "0",
        "scale": None,
        "unit": "0.1ppm",
        "od": 60,
    },
    "006": {
        "itemId": "006",
        "itemName": "浮遊粒子状物質",
        "simpleName": "SPM",
        "iniVal": "0",
        "scale": "0.001",
        "unit": "μg/m3",
        "od": 70,
    },
    "009": {
        "itemId": "009",
        "itemName": "非ﾒﾀﾝ炭化水素",
        "simpleName": "NMHC",
        "iniVal": "0",
        "scale": None,
        "unit": "pphmC",
        "od": 90,
    },
    "008": {
        "itemId": "008",
        "itemName": "メタン",
        "simpleName": "CH4",
        "iniVal": "0",
        "scale": None,
        "unit": "pphmC",
        "od": 100,
    },
    "016": {
        "itemId": "016",
        "itemName": "微小粒子状物質",
        "simpleName": "PM2.5",
        "iniVal": "0",
        "scale": None,
        "unit": "μg/m3",
        "od": 80,
    },
    "011": {
        "itemId": "011",
        "itemName": "風向",
        "simpleName": "風向",
        "iniVal": "0",
        "scale": None,
        "unit": None,
        "od": 110,
    },
    "012": {
        "itemId": "012",
        "itemName": "風速",
        "simpleName": "風速",
        "iniVal": "0",
        "scale": None,
        "unit": "0.1m/s",
        "od": 120,
    },
    "013": {
        "itemId": "013",
        "itemName": "温度",
        "simpleName": "気温",
        "iniVal": "0",
        "scale": None,
        "unit": "0.1度",
        "od": 130,
    },
    "014": {
        "itemId": "014",
        "itemName": "湿度",
        "simpleName": "湿度",
        "iniVal": "0",
        "scale": None,
        "unit": "0.1%",
        "od": 140,
    },
    "015": {
        "itemId": "015",
        "itemName": "日射量",
        "simpleName": "日射量",
        "iniVal": "0",
        "scale": None,
        "unit": "0.01MJ/m2",
        "od": 150,
    },
}
